bases:
  - git::https://repo1.dso.mil/platform-one/big-bang/umbrella.git/base?ref=disable-kustomize-suffixes

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml

patchesStrategicMerge:
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
    namespace: bigbang
  spec:
    ref:
      $patch: replace
      semver: "1.3.0"
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
  name: bigbang
    namespace: bigbang
  spec:
    valuesFrom:
      - kind: Secret
        name: terraform-creds
