bases:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=1.1.2

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml

resources:
- https://repo1.dso.mil/platform-one/big-bang/bigbang/-/raw/master/chart/ingress-certs.yaml

patchesStrategicMerge:
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
    namespace: bigbang
  spec:
    ref:
      $patch: replace
      semver: "1.1.2"
