bases:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base?ref=tags/1.14.1

configMapGenerator:
  - name: common
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml
