hostname: bigbang.dev

# Tune flux for dev
flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

istio:
  values:
    kiali:
      enabled: false
    tracing:
      enabled: false
    ingressGateway:
      maxReplicas: 1

clusterAuditor:
  enabled: false
logging:
  enabled: false
monitoring:
  enabled: false
gatekeeper:
  enabled: false
twistlock:
  enabled: false