hostname: bigbang.dev

addons:
  nexus:
    # -- Toggle deployment of Nexus.
    enabled: true
    git:
        repo: https://repo1.dso.mil/platform-one/big-bang/apps/developer-tools/nexus.git
        path: "./chart"
        tag: "29.1.0-bb.0"
